### ISSUE TITLE
Tab context menu related

### ISSUE THREAD

**Issue by henryxrl** [aminomancer/uc.css.js#17] opened 2021-11-06 17:47 UTC
1. Bookmark button
It seems like the bookmark button in the tab context menu doesn't detect whether the current page has been bookmarked or not. Please see the screenshot attached. Not sure whether it's a feature or a potential bug.

![image](https://user-images.githubusercontent.com/7662954/140618958-cb4564d9-5c2a-4e3b-ac23-82874bf7f13b.png)

2. Context menu padding
After loading the author style sheet, this happens:
![image](https://user-images.githubusercontent.com/7662954/140620512-2d59753a-3247-4840-8127-0e6fd98ed11b.png)

Do you know where I can fix this? Thanks!

**Comment by aminomancer** [comment] 2021-11-06 20:32
1. It doesn't detect whether the page is bookmarked. It's the same button no matter what. If the tab is already bookmarked then clicking it will open the edit dialog, because the edit dialog is functionally the same as the add bookmark dialog.
2. I have no idea what that is. What operating system are you using?

**Comment by henryxrl** [comment] 2021-11-06 20:33
1. I see. Thanks for the explanation.
2. It seems like an extra padding. I'm using Windows 11.

**Comment by aminomancer** [comment] 2021-11-06 20:41
Which version of Firefox?

**Comment by henryxrl** [comment] 2021-11-06 20:42
Lastest Nightly, 96.0a1 (2021-11-06) (64-bit)

**Comment by aminomancer** [comment] 2021-11-06 20:43
Also can you give me a full list of all the scripts you're using? You have all the stylesheets, right? You have the full `resources` folder and the `chrome.manifest` file?

**Comment by aminomancer** [comment] 2021-11-06 20:45
Do you have `browser.display.windows.non_native_menus` set to `1` in about:config?

**Comment by henryxrl** [comment] 2021-11-06 20:48
Yes it's 1. I set everything according to your table

**Comment by aminomancer** [comment] 2021-11-06 20:56
And no it's not extra padding. Otherwise you'd see a purple padding around it. It's blue which means it's margins on the arrowscrollbox. In the menupopup's `#shadow-root`.

I don't have Windows 11 and don't have any way to test this theme on Windows 11. Simply put it just isn't designed for Windows 11. If you can look through the inspector and tell me what you see, we can probably fix it. But I can't do it on my own. I think the shadow will be on the top level `<menupopup>` element. But the extra "padding" will be in its shadow root. Like under the `<menupopup>` there'll be a `#shadow-root` row. You expand that and there'll be an `<arrowscrollbox>` element. There should be margins on it... Like, that should show as a band of yellow bordering it. The margins will either be on the arrowscrollbox or on one of its descendants. Look around for it and when you find the yellow band, see if you can find the margin rule in the Rules tab.

Do the same with the shadow. There will probably be something like `-moz-window-shadow: cliprounded` so tell me if the problem is solved if you add `-moz-window-shadow: none !important;` and `appearance: none !important;` to userChrome.au.css.

**Comment by aminomancer** [comment] 2021-11-06 21:10
Sorry I should have said add this to userChrome.au.css:
```
menupopup, panel {
    -moz-window-shadow: none !important;
    appearance: none !important;
}
```
And maybe try adding this to userChrome.au.css too:
```
menupopup::part(content),
menupopup::part(arrowscrollbox-scrollbox) {
    margin: 0 !important;
}
```

**Comment by henryxrl** [comment] 2021-11-06 21:12
The first part of the code doesn't fix the problem but the second part does! Thank you!!!

**Comment by aminomancer** [comment] 2021-11-06 21:14
Oh I see the problem. You have `userChrome.css.menupopup-shadows` set to `true` don't you? That will create the extra padding. You should just set that to false.

**Comment by henryxrl** [comment] 2021-11-06 21:16
Ah yes! That should be the problem haha!

Btw, since you set the tabs spanning the entire width of the window, it becomes very hard to drag the window around. How do you personally do it?

**Comment by aminomancer** [comment] 2021-11-06 21:22
There's a little drag space between the window control buttons and the tab toolbar buttons (new tab, all tabs, vertical tabs buttons).
![image](https://user-images.githubusercontent.com/33384265/140624132-63391ab0-1757-4b13-b9de-ef8eb72775be.png)

When you enable the menu bar it gets a bit smaller but it's still there
![image](https://user-images.githubusercontent.com/33384265/140624157-a3810084-d863-427c-b001-72e152ac404d.png)

**Comment by aminomancer** [comment] 2021-11-06 21:24
I'd like to find some other way to allow window dragging though. I always have hundreds of tabs so they take up the full titlebar space regardless of the max tab size. So CSS wouldn't really change anything. But it might be possible to use javascript to allow window dragging on *any* element if a certain key is pressed. Like maybe if you hold down the alt key, dragging anything will drag the entire window. I'm not sure if that's possible but I'll look into it.

**Comment by henryxrl** [comment] 2021-11-06 21:28
Do you think simply leaving a small space to the left of the very first tab will do? The unmodded Firefox does have this.

![image](https://user-images.githubusercontent.com/7662954/140624296-a51d4fba-a524-4b3e-9219-d0be6b348298.png)
![image](https://user-images.githubusercontent.com/7662954/140624307-713b329a-f56b-4c48-9ae4-ff103fd7cf25.png)

**Comment by aminomancer** [comment] 2021-11-06 22:08
No I removed the space on purpose because I think it looks ugly. [Try this script](https://github.com/aminomancer/uc.css.js#window-drag-hotkey)

**Closed by aminomancer** 2021-11-06 22:08 UTC

**Comment by henryxrl** [comment] 2021-11-06 22:13
Wow this works nice! For me, holding shift and dragging windows triggers Microsoft's PowerToy FancyZones. I'd have to change the hotkey from alt+shift to ctrl+shift. Great work!
